@startuml C4_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(Consultant, "Сотрудник кол-центра", "Консультирует клиентов по телефону")
Person(PartnerConsultant, "Сотрудник партнёрского кол-центра", "Консультирует клиентов по телефону")
Person(Client, "Клиент", "Звонит в кол-центр по ставкам")

System_Boundary(Bank, "Банк «Стандарт»") {
  System(ABS, "АБС", "Oracle + PL/SQL", "Хранит актуальные депозитные ставки и журнал аудита")
  System(ExportService, "Сервис экспорта ставок", "C#/.NET", "Генерирует, шифрует и отдает ставки")
  System(CRM, "CRM кол-центра", "Java + PostgreSQL")
  System_Ext(PartnerCRM, "Кол-центр партнёра", "Внешняя система", "Скачивает ставки для консультации клиентов")
  System_Ext(SFTP, "SFTP-сервер", "OpenSSH + SSL", "Хранит PGP-зашифрованные CSV-файлы")
  System_Ext(Monitoring, "Система мониторинга", "Prometheus + Grafana", "Следит за SLA и доступностью канала")
}

Rel(Client, Consultant, "Звонит для уточнения ставки")
Rel(Consultant, CRM, "Использует UI")
Rel(CRM, ExportService, "GET /rates (OAuth2 + mTLS)")
Rel(ExportService, ABS, "ODBC/PL-SQL: читает депозитные ставки")
Rel(ExportService, SFTP, "SFTP+SSL: загружает PGP-CSV")
Rel(PartnerCRM, SFTP, "SFTP: скачивает PGP-CSV")
Rel(ExportService, Monitoring, "Метрики выгрузок и ошибок")
Rel(SFTP, Monitoring, "Метрики доступности канала")

@enduml


